<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist><dict><key>injectionSelector</key><string>L:comment.block.documentation</string><key>patterns</key><array><dict><key>include</key><string>#markdown-comment</string></dict></array><key>repository</key><dict><key>markdown-comment</key><dict><key>begin</key><string>(?&lt;=/\*\*)([^*]|\*(?!/))*$</string><key>while</key><string>(^|\G)\s*(?:\*(?![*\w]))?(?!\/)(?=([^*]|[*](?!\/))*$)</string><key>patterns</key><array><dict><key>include</key><string>text.html.markdown#fenced_code_block</string></dict><dict><key>include</key><string>text.html.markdown#lists</string></dict><dict><key>include</key><string>source.hx#javadoc-tags</string></dict><dict><key>include</key><string>text.html.markdown#inline</string></dict></array></dict></dict><key>scopeName</key><string>documentation.markdown.injection.haxe</string></dict></plist>