<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist><dict><key>injectionSelector</key><string>L:markup.fenced_code.block.markdown</string><key>scopeName</key><string>markdown.hxml.codeblock</string><key>repository</key><dict><key>hxml-code-block</key><dict><key>end</key><string>(^|\G)(?=\s*[`~]{3,}\s*$)</string><key>begin</key><string>hxml(\s+[^`~]*)?$</string><key>patterns</key><array><dict><key>while</key><string>(^|\G)(?!\s*([`~]{3,})\s*$)</string><key>contentName</key><string>meta.embedded.block.hxml</string><key>begin</key><string>(^|\G)(\s*)(.*)</string><key>patterns</key><array><dict><key>include</key><string>source.hxml</string></dict></array></dict></array></dict></dict><key>patterns</key><array><dict><key>include</key><string>#hxml-code-block</string></dict></array></dict></plist>